version: '3.0'
services:

  memcached:
    image: memcached:latest
    container_name: api_memcached
    expose:
      - "11211"

  nginx:
    image: nginx:latest
    container_name: api_nginx_1
    ports:
      - "8000:8000"
    volumes:
      - ./confs/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    command: bash -c "nginx -g 'daemon off;'"

  web:
    build: .
    container_name: api_django_1
    command: bash ./setup.sh
    depends_on:
      - memcached
    expose:
      - "8000"
